name: CI workflow

# Workflow Triggers: Run on push and pull_request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Define the container with Python 3.9
    container:
      image: python:3.9-slim

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
